export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOAD_USERS_BY_ID_START = "LOAD_USERS_BY_ID_START";
export const LOAD_USERS_BY_ID_SUCCESS = "LOAD_USERS_BY_ID_SUCCESS";
export const LOAD_USERS_BY_ID_ERROR = "LOAD_USERS_BY_ID_ERROR";

export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const GET_SINGLE_USER_START = "GET_SINGLE_USER_START";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_ERROR = "GET_SINGLE_USER_ERROR";

export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS_ERROR";

export const LOAD_SINGLE_PRODUCT_START = "LOAD_SINGLE_PRODUCT_START";
export const LOAD_SINGLE_PRODUCT_SUCCESS = "LOAD_SINGLE_PRODUCT_SUCCESS";
export const LOAD_SINGLE_PRODUCT_ERROR = "LOAD_SINGLE_PRODUCT_ERROR";

export const ADD_CART_START = "ADD_CART_START";
export const ADD_CART = "ADD_CART";

export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_START = "DELETE_CART_START";

export const INCREASE_QUANTITY_START = "INCREASE_QUANTITY_START";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";

export const DECREASE_QUANTITY_START = "DECREASE_QUANTITY_START";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
